# file.py
print(f"Name: {user['name']}")
print(f"Age: {user['age']}")
print(f"Error here: {user['name']}")
print(f"Test")
print(f"Address: {user['address']}")
print(f"Nested issue: {user['nested']['key']}")
print(f"Value with double quotes: {user['\"key\"']}")
print(f"Something simple")
print(f"Correct usage: {user['key']}")
print("This line doesn't have an f-string")
print(f"Another f-string: {data['value']}")
print(f"Complex: {nested['structure']['with']['quotes']}")
print(f"Error again: {data["key"]}")
print(f"Edge case: {json.dumps({'key': 'value'})}")
print(f"Another test: {something['else']}")
print(f"Nothing wrong here")
print(f"Check this: {obj['attr']}")
print(f"Problem here: {user["attribute"]}")
print(f"More data: {info['details']}")
print(f"Valid f-string: {get_value('key')}")
print(f"Value: {value['data']}")
print(f"Nested quotes: {deeply["nested"]["item"]}")
print(f"Another valid one")
print(f"Oops: {oops['error']}")
print(f"Check: {check_this['field']}")
print(f"Good: {something['valid']}")
print(f"Yet another one: {user['value']}")
print(f"Valid again: {data['input']}")
print(f"Quotes issue: {nested["field"]["subfield"]}")
print(f"Some text here")
print(f"Valid line")
print(f"Invalid: {test["field"]}")
print(f"Here's a normal line")
print(f"Correct: {x['y']}")
print(f"Another valid f-string: {key['val']}")
print(f"Error: {user["x"]["y"]}")
print(f"OK: {data['okay']}")
print(f"More text")
print(f"Final valid one: {last['item']}")
print(f"Edge case again: {structure['"key"']}")
print(f"Good to go")
print(f"Simple")
print(f"Invalid: {item["invalid"]}")
print(f"Quotes here: {obj['attribute']}")
print(f"Final test")
print(f"Last invalid: {user["final"]}")

